site_name: FRC Attendance Tracker
repo_url: https://github.com/meowmeowahr/attendance_tracker_prototype_flutter

theme:
  name: material
  language: en
  features:
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer
    - navigation.indexes
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: red
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: red
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: red
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
nav:
  - index.md
  - Installation:
      - install/android.md
  - User Guide:
      - Configuration:
          - config/index.md
          - config/androidlock.md
  - RFID Hardware: rfid.md

extra:
  version:
    provider: mike

plugins:
  - search

markdown_extensions:
  - admonition